nf_core_version: 3.4.1
repository_type: pipeline
template:
  author: Chelsea Sawyer, Edmund Miller, Matthias De Smet
  description: Demultiplexing pipeline for Illumina sequencing data
  force: false
  is_nfcore: true
  name: demultiplex
  org: nf-core
  outdir: .
  skip_features:
    - igenomes
  version: 1.7.0
