nf_core_version: 3.3.2
repository_type: pipeline
template:
  author: Chelsea Sawyer, Edmund Miller, Matthias De Smet
  description: Demultiplexing pipeline for Illumina sequencing data
  force: false
  is_nfcore: true
  name: demultiplex
  org: nf-core
  outdir: .
  skip_features:
    - igenomes
  version: 1.6.2dev
